name: Auto Merge Dependency Updates

on:
  - pull_request

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: tjenkinson/gh-action-auto-merge-dependency-updates@5a9e8e4
        with:
          allowed-actors: dependabot-preview[bot], dependabot[bot]
          allowed-update-types: devDependencies:minor, devDependencies:patch, dependencies:minor, dependencies:patch
